Fix : NPE in ModelBasedPossibleValuesService
An exception is seen when deleting an item in the catalog sample.

java.lang.RuntimeException: Item.Category: ModelBasedPossibleValuesService.compute() has failed
	at org.eclipse.sapphire.services.DataService.refresh(DataService.java:130)
	at org.eclipse.sapphire.internal.ModelBasedPossibleValuesService.access$0(ModelBasedPossibleValuesService.java:1)
	at org.eclipse.sapphire.internal.ModelBasedPossibleValuesService$1.handleTypedEvent(ModelBasedPossibleValuesService.java:68)
	at org.eclipse.sapphire.internal.ModelBasedPossibleValuesService$1.handleTypedEvent(ModelBasedPossibleValuesService.java:1)
	at org.eclipse.sapphire.FilteredListener.handle(FilteredListener.java:35)
	at org.eclipse.sapphire.EventDeliveryJob.run(EventDeliveryJob.java:52)
	at org.eclipse.sapphire.JobQueue.process(JobQueue.java:94)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:126)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:132)
	at org.eclipse.sapphire.ui.SapphirePart.broadcast(SapphirePart.java:560)
	at org.eclipse.sapphire.ui.SapphirePart.dispose(SapphirePart.java:877)
	at org.eclipse.sapphire.ui.forms.MasterDetailsContentNodePart.dispose(MasterDetailsContentNodePart.java:763)
	at org.eclipse.sapphire.ui.forms.MasterDetailsContentNodePart$NodeFactory.nodes(MasterDetailsContentNodePart.java:1026)
	at org.eclipse.sapphire.ui.forms.MasterDetailsContentNodePart.refreshNodes(MasterDetailsContentNodePart.java:689)
	at org.eclipse.sapphire.ui.forms.MasterDetailsContentNodePart.access$0(MasterDetailsContentNodePart.java:677)
	at org.eclipse.sapphire.ui.forms.MasterDetailsContentNodePart$NodeFactory$1.handle(MasterDetailsContentNodePart.java:894)
	at org.eclipse.sapphire.EventDeliveryJob.run(EventDeliveryJob.java:52)
	at org.eclipse.sapphire.JobQueue.process(JobQueue.java:94)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:126)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:132)
	at org.eclipse.sapphire.Property.broadcast(Property.java:766)
	at org.eclipse.sapphire.ElementList.refreshContent(ElementList.java:214)
	at org.eclipse.sapphire.ElementList.refresh(ElementList.java:82)
	at org.eclipse.sapphire.ElementList.remove$(ElementList.java:601)
	at org.eclipse.sapphire.ElementList.remove(ElementList.java:591)
	at org.eclipse.sapphire.ui.forms.internal.OutlineNodeDeleteActionHandler.run(OutlineNodeDeleteActionHandler.java:79)
	at org.eclipse.sapphire.ui.SapphireActionHandler.execute(SapphireActionHandler.java:95)
	at org.eclipse.sapphire.ui.forms.swt.SapphireMenuActionPresentation$2.widgetSelected(SapphireMenuActionPresentation.java:125)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1122)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1006)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:147)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:630)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:574)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:125)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:133)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:103)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:378)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:232)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1462)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
Caused by: java.lang.NullPointerException
	at org.eclipse.sapphire.PossibleValuesService.compute(PossibleValuesService.java:91)
	at org.eclipse.sapphire.PossibleValuesService.compute(PossibleValuesService.java:1)
	at org.eclipse.sapphire.services.DataService.refresh(DataService.java:103)
	... 55 more

Bugzilla: https://bugs.eclipse.org/bugs/show_bug.cgi?id=430744