Fix : Validation of column types in a foreign key
The management of listeners is faulty, leading to leaked listeners and
exceptions in some cases.

java.lang.RuntimeException: ForeignKey.ColumnAssociations: FKColumnAssociationValidator.compute() has failed
	at org.eclipse.sapphire.services.DataService.refresh(DataService.java:130)
	at org.eclipse.sapphire.samples.sqlschema.FKColumnAssociationValidator.access$1(FKColumnAssociationValidator.java:1)
	at org.eclipse.sapphire.samples.sqlschema.FKColumnAssociationValidator$1.handleTypedEvent(FKColumnAssociationValidator.java:47)
	at org.eclipse.sapphire.samples.sqlschema.FKColumnAssociationValidator$1.handleTypedEvent(FKColumnAssociationValidator.java:1)
	at org.eclipse.sapphire.FilteredListener.handle(FilteredListener.java:35)
	at org.eclipse.sapphire.ListenerContext$BroadcastJob.run(ListenerContext.java:193)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:131)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:138)
	at org.eclipse.sapphire.services.Service.broadcast(Service.java:129)
	at org.eclipse.sapphire.services.Service.broadcast(Service.java:134)
	at org.eclipse.sapphire.services.DataService.refresh(DataService.java:152)
	at org.eclipse.sapphire.services.internal.FunctionBasedEnablementService.access$1(FunctionBasedEnablementService.java:1)
	at org.eclipse.sapphire.services.internal.FunctionBasedEnablementService$1.handle(FunctionBasedEnablementService.java:53)
	at org.eclipse.sapphire.ListenerContext$BroadcastJob.run(ListenerContext.java:193)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:131)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:138)
	at org.eclipse.sapphire.modeling.el.FunctionResult.refresh(FunctionResult.java:294)
	at org.eclipse.sapphire.modeling.el.FunctionResult.refresh(FunctionResult.java:251)
	at org.eclipse.sapphire.modeling.el.FunctionResult$1.handle(FunctionResult.java:88)
	at org.eclipse.sapphire.ListenerContext$BroadcastJob.run(ListenerContext.java:193)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:131)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:138)
	at org.eclipse.sapphire.modeling.el.FunctionResult.refresh(FunctionResult.java:294)
	at org.eclipse.sapphire.modeling.el.FunctionResult.refresh(FunctionResult.java:251)
	at org.eclipse.sapphire.modeling.el.FunctionResult$1.handle(FunctionResult.java:88)
	at org.eclipse.sapphire.ListenerContext$BroadcastJob.run(ListenerContext.java:193)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:131)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:138)
	at org.eclipse.sapphire.ui.SapphirePart.broadcast(SapphirePart.java:560)
	at org.eclipse.sapphire.ui.diagram.editor.TextPart.access$0(TextPart.java:1)
	at org.eclipse.sapphire.ui.diagram.editor.TextPart$1.run(TextPart.java:62)
	at org.eclipse.sapphire.ui.SapphirePart$1$1.run(SapphirePart.java:267)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:187)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:150)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4731)
	at org.eclipse.sapphire.ui.SapphirePart$1.handle(SapphirePart.java:272)
	at org.eclipse.sapphire.ListenerContext$BroadcastJob.run(ListenerContext.java:193)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:131)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:138)
	at org.eclipse.sapphire.modeling.el.FunctionResult.refresh(FunctionResult.java:294)
	at org.eclipse.sapphire.modeling.el.FunctionResult.refresh(FunctionResult.java:251)
	at org.eclipse.sapphire.modeling.el.FunctionResult$1.handle(FunctionResult.java:88)
	at org.eclipse.sapphire.ListenerContext$BroadcastJob.run(ListenerContext.java:193)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:131)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:138)
	at org.eclipse.sapphire.modeling.el.FunctionResult.refresh(FunctionResult.java:294)
	at org.eclipse.sapphire.modeling.el.FunctionResult.refresh(FunctionResult.java:251)
	at org.eclipse.sapphire.modeling.el.ConditionalFunction$1$1.handle(ConditionalFunction.java:75)
	at org.eclipse.sapphire.ListenerContext$BroadcastJob.run(ListenerContext.java:193)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:131)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:138)
	at org.eclipse.sapphire.modeling.el.FunctionResult.refresh(FunctionResult.java:294)
	at org.eclipse.sapphire.modeling.el.FunctionResult.refresh(FunctionResult.java:251)
	at org.eclipse.sapphire.modeling.el.PropertyAccessFunction$1$1.handle(PropertyAccessFunction.java:93)
	at org.eclipse.sapphire.ListenerContext$BroadcastJob.run(ListenerContext.java:193)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:131)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:138)
	at org.eclipse.sapphire.modeling.el.FunctionResult.refresh(FunctionResult.java:294)
	at org.eclipse.sapphire.modeling.el.FunctionResult.refresh(FunctionResult.java:251)
	at org.eclipse.sapphire.modeling.el.DeferredFunction$1$1.handle(DeferredFunction.java:175)
	at org.eclipse.sapphire.ListenerContext$BroadcastJob.run(ListenerContext.java:193)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:131)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:138)
	at org.eclipse.sapphire.modeling.el.FunctionResult.refresh(FunctionResult.java:294)
	at org.eclipse.sapphire.modeling.el.FunctionResult.refresh(FunctionResult.java:251)
	at org.eclipse.sapphire.modeling.el.FunctionResult$1.handle(FunctionResult.java:88)
	at org.eclipse.sapphire.ListenerContext$BroadcastJob.run(ListenerContext.java:193)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:131)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:138)
	at org.eclipse.sapphire.Property.broadcast(Property.java:714)
	at org.eclipse.sapphire.Value.refreshContent(Value.java:145)
	at org.eclipse.sapphire.Value.refresh(Value.java:67)
	at org.eclipse.sapphire.Value.write(Value.java:414)
	at org.eclipse.sapphire.ui.swt.gef.commands.LabelNodeCommand.execute(LabelNodeCommand.java:64)
	at org.eclipse.gef.commands.CommandStack.execute(CommandStack.java:199)
	at org.eclipse.sapphire.ui.swt.gef.internal.ComboBoxDirectEditorManager.applyEditorValue(ComboBoxDirectEditorManager.java:125)
	at org.eclipse.sapphire.ui.swt.gef.internal.ComboBoxDirectEditorManager.access$0(ComboBoxDirectEditorManager.java:112)
	at org.eclipse.sapphire.ui.swt.gef.internal.ComboBoxDirectEditorManager$1.applyEditorValue(ComboBoxDirectEditorManager.java:107)
	at org.eclipse.jface.viewers.CellEditor$1.run(CellEditor.java:336)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:49)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:178)
	at org.eclipse.jface.viewers.CellEditor.fireApplyEditorValue(CellEditor.java:333)
	at org.eclipse.jface.viewers.ComboBoxCellEditor.applyEditorValueAndDeactivate(ComboBoxCellEditor.java:283)
	at org.eclipse.jface.viewers.ComboBoxCellEditor.focusLost(ComboBoxCellEditor.java:295)
	at org.eclipse.jface.viewers.ComboBoxCellEditor$4.focusLost(ComboBoxCellEditor.java:176)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:143)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1085)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1070)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:782)
	at org.eclipse.swt.custom.CCombo.handleFocus(CCombo.java:906)
	at org.eclipse.swt.custom.CCombo$2.handleEvent(CCombo.java:147)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1262)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1085)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Control.sendFocusEvent(Control.java:2841)
	at org.eclipse.swt.widgets.Widget.wmSetFocus(Widget.java:2425)
	at org.eclipse.swt.widgets.Control.WM_SETFOCUS(Control.java:5236)
	at org.eclipse.swt.widgets.Canvas.WM_SETFOCUS(Canvas.java:456)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4680)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:339)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5020)
	at org.eclipse.swt.internal.win32.OS.SetFocus(Native Method)
	at org.eclipse.swt.widgets.Control.forceFocus(Control.java:1097)
	at org.eclipse.gef.ui.parts.DomainEventDispatcher.dispatchMousePressed(DomainEventDispatcher.java:346)
	at org.eclipse.draw2d.LightweightSystem$EventHandler.mouseDown(LightweightSystem.java:523)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:192)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1122)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1006)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:147)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:630)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:574)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:125)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:133)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:103)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:378)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:232)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1462)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
Caused by: java.lang.IllegalStateException: ForeignKey element is already disposed.
	at org.eclipse.sapphire.ElementImpl.assertNotDisposed(ElementImpl.java:1042)
	at org.eclipse.sapphire.ElementImpl.property(ElementImpl.java:402)
	at org.eclipse.sapphire.samples.sqlschema.ForeignKey$Impl.getColumnAssociations(Unknown Source)
	at org.eclipse.sapphire.samples.sqlschema.FKColumnAssociationValidator.compute(FKColumnAssociationValidator.java:91)
	at org.eclipse.sapphire.samples.sqlschema.FKColumnAssociationValidator.compute(FKColumnAssociationValidator.java:1)
	at org.eclipse.sapphire.services.DataService.refresh(DataService.java:103)
	... 138 more

Bugzilla: https://bugs.eclipse.org/bugs/show_bug.cgi?id=430234